export { default as Navbar} from './Navbar'
export {default as Homepage} from './HomePage'
export {default as Exchanges} from './Exchanges'
export {default as Cryptocurrncies} from './Cryptocurrncies'
export {default as CryptoDetails} from './CryptoDetails'
export {default as News} from './News'